// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYltxC0o7UBYHP9_yJYFjvb6xMl-m00kI',
    appId: '1:496531737502:web:9195d217e8cfe66fa3a48f',
    messagingSenderId: '496531737502',
    projectId: 'bluenotify-b1700',
    authDomain: 'bluenotify-b1700.firebaseapp.com',
    storageBucket: 'bluenotify-b1700.firebasestorage.app',
    measurementId: 'G-TGZP96GVD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCete8RIL_y_xNbyeISdUKrvN0tuRlyeyM',
    appId: '1:496531737502:android:0fe8dec417982600a3a48f',
    messagingSenderId: '496531737502',
    projectId: 'bluenotify-b1700',
    storageBucket: 'bluenotify-b1700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqQ6yvvQIy6hyKSoMuvPt5RXe2vyqcuc',
    appId: '1:496531737502:ios:4b0471cd676d269fa3a48f',
    messagingSenderId: '496531737502',
    projectId: 'bluenotify-b1700',
    storageBucket: 'bluenotify-b1700.firebasestorage.app',
    iosBundleId: 'com.austinwitherspoon.blueNotify',
  );
}
